# Site settings
title: 101 Environmental
email: info@101environmental.com
description: Falconry and pest control in Gloucestershire, Wiltshire and South Wales
baseurl: "/"
url: "http://www.101environmental.com" # the base hostname & protocol for your site

instagram_username: 101environmental

# Build settings
markdown: kramdown
